services:
  frontend:
    build:
      context: ./frontend
    container_name: ecc-frontend
    environment:
      VITE_BACKEND_URL: http://127.0.0.1:5001
    ports: 
      - "5173:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: ecc-backend
    ports:
      - "5001:5001"